export const GET_ASSET_REQUEST = 'GET_ASSET_REQUEST';
export const GET_ASSET_SUCCESS = 'GET_ASSET_SUCCESS';

export const GET_PRE_CORPUS_CALCULATION_REQUEST = 'GET_PRE_CORPUS_CALCULATION_REQUEST';
export const GET_PRE_CORPUS_CALCULATION_SUCCESS = 'GET_PRE_CORPUS_CALCULATION_SUCCESS';