export const GET_NOMINEE_RELEATION_REQUEST = 'GET_NOMINEE_RELEATION_REQUEST';
export const GET_NOMINEE_RELEATION_SUCCESS = 'GET_NOMINEE_RELEATION_SUCCESS';

export const GET_WEALTH_LIST_REQUEST = 'GET_WEALTH_LIST_REQUEST';
export const GET_WEALTH_LIST_SUCCESS = 'GET_WEALTH_LIST_SUCCESS';

export const GET_COUNTRY_LIST_REQUEST = 'GET_COUNTRY_LIST_REQUEST';
export const GET_COUNTRY_LIST_SUCCESS = 'GET_COUNTRY_LIST_SUCCESS';

export const GET_STATE_LIST_REQUEST = 'GET_STATE_LIST_REQUEST';
export const GET_STATE_LIST_SUCCESS = 'GET_STATE_LIST_SUCCESS';

export const GET_OCCUPATION_LIST_REQUEST = 'GET_OCCUPATION_LIST_REQUEST';
export const GET_OCCUPATION_LIST_SUCCESS = 'GET_OCCUPATION_LIST_SUCCESS';

export const GET_INCOME_SLAB_LIST_REQUEST = 'GET_INCOME_SLAB_LIST_REQUEST';
export const GET_INCOME_SLAB_LIST_SUCCESS = 'GET_INCOME_SLAB_LIST_SUCCESS';

export const GET_BANK_ACCOUNT_TYPES_REQUEST = 'GET_BANK_ACCOUNT_TYPES_REQUEST';
export const GET_BANK_ACCOUNT_TYPES_SUCCESS = 'GET_BANK_ACCOUNT_TYPES_SUCCESS';

export const UPDATE_BSE_ACCOUNT_CREATION_REQUEST = 'UPDATE_BSE_ACCOUNT_CREATION_REQUEST';
export const UPDATE_BSE_ACCOUNT_CREATION_SUCCESS = 'UPDATE_BSE_ACCOUNT_CREATION_SUCCESS';

export const ADD_BSE_ACCOUNT_NOMINEE_REQUEST = 'ADD_BSE_ACCOUNT_NOMINEE_REQUEST';
export const ADD_BSE_ACCOUNT_NOMINEE_SUCCESS = 'ADD_BSE_ACCOUNT_NOMINEE_SUCCESS';

export const GET_BSE_ACCOUNT_NOMINEES_REQUEST = 'GET_BSE_ACCOUNT_NOMINEES_REQUEST';
export const GET_BSE_ACCOUNT_NOMINEES_SUCCESS = 'GET_BSE_ACCOUNT_NOMINEES_SUCCESS';

export const UPDATE_BSE_ACCOUNT_NOMINEE_REQUEST = 'UPDATE_BSE_ACCOUNT_NOMINEE_REQUEST';
export const UPDATE_BSE_ACCOUNT_NOMINEE_SUCCESS = 'UPDATE_BSE_ACCOUNT_NOMINEE_SUCCESS';

export const DELETE_BSE_ACCOUNT_NOMINEE_REQUEST = 'DELETE_BSE_ACCOUNT_NOMINEE_REQUEST';
export const DELETE_BSE_ACCOUNT_NOMINEE_SUCCESS = 'DELETE_BSE_ACCOUNT_NOMINEE_SUCCESS';

export const ADD_BSE_BANK_ACCOUNT_REQUEST = 'ADD_BSE_BANK_ACCOUNT_REQUEST';
export const ADD_BSE_BANK_ACCOUNT_SUCCESS = 'ADD_BSE_BANK_ACCOUNT_SUCCESS';

export const GET_BSE_BANK_ACCOUNT_REQUEST = 'GET_BSE_BANK_ACCOUNT_REQUEST';
export const GET_BSE_BANK_ACCOUNT_SUCCESS = 'GET_BSE_BANK_ACCOUNT_SUCCESS';

export const UPDATE_BSE_BANK_ACCOUNT_REQUEST = 'UPDATE_BSE_BANK_ACCOUNT_REQUEST';
export const UPDATE_BSE_BANK_ACCOUNT_SUCCESS = 'UPDATE_BSE_BANK_ACCOUNT_SUCCESS';

export const DELETE_BSE_BANK_ACCOUNT_REQUEST = 'DELETE_BSE_BANK_ACCOUNT_REQUEST';
export const DELETE_BSE_BANK_ACCOUNT_SUCCESS = 'DELETE_BSE_BANK_ACCOUNT_SUCCESS';








