export const GET_GOAL_CATEGORY_REQUEST  = 'GET_GOAL_CATEGORY_REQUEST';
export const GET_GOAL_CATEGORY_SUCCESS =  'GET_GOAL_CATEGORY_SUCCESS';
export const GET_GOAL_BUCKET_REQUEST =    'GET_GOAL_BUCKET_REQUEST';
export const GET_GOAL_BUCKET_SUCCESS =    'GET_GOAL_BUCKET_SUCCESS';
export const GET_GOAL_FREQUENCY_REQUEST = 'GET_GOAL_FREQUENCY_REQUEST';
export const GET_GOAL_FREQUENCY_SUCCESS = 'GET_GOAL_FREQUENCY_SUCCESS';
export const GET_GOAL_TYPE_REQUEST = 'GET_GOAL_TYPE_REQUEST';
export const GET_GOAL_TYPE_SUCCESS = 'GET_GOAL_TYPE_SUCCESS';
export const ADD_GOALS_REQUEST = 'ADD_GOALS_REQUEST';
export const ADD_GOALS_SUCCESS = 'ADD_GOALS_SUCCESS';
export const GET_USER_ALL_GOALS_REQUEST = 'GET_USER_ALL_GOALS_REQUEST';
export const GET_USER_ALL_GOALS_SUCCESS = 'GET_USER_ALL_GOALS_SUCCESS';
export const DELETE_GOALS_REQUEST = 'DELETE_GOALS_REQUEST';
export const DELETE_GOALS_REQUEST_SUCCESS = 'DELETE_GOALS_REQUEST_SUCCESS';

export const GET_GOAL_RATE_REQUEST = 'GET_GOAL_RATE_REQUEST';
export const GET_GOAL_RATE_SUCCESS = 'GET_GOAL_RATE_SUCCESS';