export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_PASSWORD_CHANGE = 'SET_PASSWORD_CHANGE';
export const SET_EMAIL_CHANGE = 'SET_EMAIL_CHANGE';
export const RESET_VALUES = 'RESET_VALUES';