export const GET_INCOME_CATEGORY_REQUEST  = 'GET_INCOME_CATEGORY_REQUEST';
export const GET_INCOME_CATEGORY_REQUEST_SUCCESS =  'GET_INCOME_CATEGORY_REQUEST_SUCCESS';

export const GET_INCOME_TYPE_REQUEST = 'GET_INCOME_TYPE_REQUEST';
export const GET_INCOME_TYPE_REQUEST_SUCCESS = 'GET_INCOME_TYPE_REQUEST_SUCCESS';

export const GET_USER_INCOME_REQUEST = 'GET_USER_INCOME_REQUEST';
export const GET_USER_INCOME_REQUEST_SUCCESS = 'GET_USER_INCOME_REQUEST_SUCCESS';

export const SAVE_USER_INCOME_REQUEST = 'SAVE_USER_INCOME_REQUEST';
export const SAVE_USER_INCOME_REQUEST_SUCCESS = 'SAVE_USER_INCOME_REQUEST_SUCCESS';

export const DELETE_USER_INCOME_REQUEST = 'DELETE_USER_INCOME_REQUEST';
export const DELETE_USER_INCOME_REQUEST_SUCCESS = 'DELETE_USER_INCOME_REQUEST_SUCCESS';


export const GET_INCOME_FREQUENCY_REQUEST = 'GET_INCOME_FREQUENCY_REQUEST';
export const GET_INCOME_FREQUENCY_SUCCESS = 'GET_INCOME_FREQUENCY_SUCCESS';
