export const GET_RISKPROFILESCORE_REQUEST = 'GET_RISKPROFILESCORE_REQUEST';
export const GET_RISKPROFILESCORE_SUCCESS = 'GET_RISKPROFILESCORE_SUCCESS';
export const GET_RISKPROFILESCORE_QUESTIONS_REQUEST = 'GET_RISKPROFILESCORE_QUESTIONS_REQUEST';
export const GET_RISKPROFILESCORE_QUESTIONS_SUCCESS = 'GET_RISKPROFILESCORE_QUESTIONS_SUCCESS';
export const SAVE_RISKPROFILESCORE_REDUCER = 'SAVE_RISKPROFILESCORE_REDUCER';
export const SAVE_RISKPROFILE_ANSWERS_REQUEST = 'SAVE_RISKPROFILE_ANSWERS_REQUEST';
export const SAVE_RISKPROFILE_ANSWERS_SUCCESS = 'SAVE_RISKPROFILE_ANSWERS_SUCCESS';

export const UPDATE_QUESTIONS = 'UPDATE_QUESTIONS';

export const CLEAR_ANSWERS = 'CLEAR_ANSWERS';


