export const GET_RRSCORE_REQUEST = 'GET_RRSCORE_REQUEST';
export const GET_RRSCORE_SUCCESS = 'GET_RRSCORE_SUCCESS';
export const GET_RRSCORE_QUESTIONS_REQUEST = 'GET_RRSCORE_QUESTIONS_REQUEST';
export const GET_RRSCORE_QUESTIONS_SUCCESS = 'GET_RRSCORE_QUESTIONS_SUCCESS';
export const SAVE_RRSCORE_REDUCER = 'SAVE_RRSCORE_REDUCER';
export const GET_ASSET_REQUEST = 'GET_ASSET_REQUEST';
export const GET_ASSET_SUCCESS = 'GET_ASSET_SUCCESS';
export const SAVE_RRSCORE_ANSWERS_REQUEST = 'SAVE_RRSCORE_ANSWERS_REQUEST';
export const SAVE_RRSCORE_ANSWERS_SUCCESS = 'SAVE_RRSCORE_ANSWERS_SUCCESS';
export const CLEAR_RRSCORE_REDUCER = 'CLEAR_RRSCORE_REDUCER';
export const GET_SSCORE_REQUEST = 'GET_SSCORE_REQUEST';
export const GET_SSCORE_SUCCESS = 'GET_SSCORE_SUCCESS';
export const SAVE_SS_SCORE_REDUCER = 'SAVE_SS_SCORE_REDUCER';



