export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGIN_USER_REQUEST    = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS    = 'LOGIN_USER_SUCCESS';
export const GET_RETIREMENT_STATUS_REQUEST = 'GET_RETIREMENT_STATUS_REQUEST';
export const GET_RETIREMENT_STATUS_SUCCESS = 'GET_RETIREMENT_STATUS_SUCCESS';
export const GET_MARITAL_STATUS_REQUEST = 'GET_MARITAL_STATUS_REQUEST';
export const GET_MARITAL_STATUS_SUCCESS = 'GET_MARITAL_STATUS_SUCCESS';
export const GET_GENDER_LIST_REQUEST  = 'GET_GENDER_LIST_REQUEST';
export const GET_GENDER_LIST_SUCCESS = 'GET_GENDER_LIST_SUCCESS';
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const UPDATE_USER = 'UPDATE_USER';
export const PANCARD_VERIFICATION_REQUEST = 'PANCARD_VERIFICATION_REQUEST';
export const PANCARD_VERIFICATION_SUCCESS = 'PANCARD_VERIFICATION_SUCCESS';
export const IFSC_CODE_REQUEST = 'IFSC_CODE_REQUEST';
export const IFSC_CODE_SUCCESS = 'IFSC_CODE_SUCCESS';
export const SET_PAYMENT_REQUEST = 'SET_PAYMENT_REQUEST';
export const SET_PAYMENT_SUCCESS = 'SET_PAYMENT_SUCCESS';
export const SET_BSE_ACCOUNT_REQUEST = 'SET_BSE_ACCOUNT_REQUEST';
export const SET_BSE_ACCOUNT_SUCCESS = 'SET_BSE_ACCOUNT_SUCCESS';
export const GET_USER_PHONE_VERIFIED_REQUEST = 'GET_USER_PHONE_VERIFIED_REQUEST';
export const GET_USER_PHONE_VERIFIED_SUCCESS = 'GET_USER_PHONE_VERIFIED_SUCCESS';
export const ADD_USER_PHONE_VERIFIED_REQUEST = 'ADD_USER_PHONE_VERIFIED_REQUEST';
export const ADD_USER_PHONE_VERIFIED_SUCCESS = 'ADD_USER_PHONE_VERIFIED_SUCCESS';
export const UPDATE_USER_PHONE_VERIFIED_REQUEST = 'UPDATE_USER_PHONE_VERIFIED_REQUEST';
export const UPDATE_USER_PHONE_VERIFIED_SUCCESS = 'UPDATE_USER_PHONE_VERIFIED_SUCCESS';
export const UPDATE_USER_INFORMATION_REQUEST = 'UPDATE_USER_INFORMATION_REQUEST';
export const UPDATE_USER_INFORMATION_SUCCESS = 'UPDATE_USER_INFORMATION_SUCCESS';








